### ISSUE TITLE
Issue Template -- Draft

### ISSUE THREAD

**Issue by kotp** [kotp/xruby#1]
## Expected Behavior
The files in `.github/` folder holds the template for issue and pull request.

When you create an issue, it has comments (should be deleted, but will stay out of the way) that help to ensure all things required will be included in the pull request or issue.

## Current Behavior

Need to test this on master, otherwise it does not pick up, so doing so in [kotp/xruby](https://github.com/kotp/xruby) on master is appropriate

The risk, of course, is that I push to exercism with this in flux.  (I have done it once, reverted it, no damage done, but... yeah, the risk is there).

## Possible Solution
I would like to take the things that were mentioned in the recent Behind the Scenes newsletter in regards to issues and pull requests, and make it easy for new contributers.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

## Task List

* [ ] Add Task List into Template
* [ ] Add commented out reference links
* [ ] Have @Insti review.

## references and closures

See comment to see samples of reference and closure "magic comments"

```
<!--- references #000 --->
<!--- closes #000 -->
```

**Comment by kotp** [comment]
This close of the exercism/xruby repository has a default branch of DEV which changes things a little bit.  This means that we can now modify the templates and not risk pushing to master changes that are transitory.  This also lets me have a staging area and lets me decide when master gets updated from either and all sources.
